### ISSUE TITLE
[query] `hl.vds.new_combiner` gives LPGT the wrong type in Hail 0.2.120

### ISSUE THREAD

**Issue by jmarshall** [hail-is/hail#13337]
### What happened?

A test case of ours (see populationgenomics/production-pipelines#424) newly abends with Hail 0.2.120. In essence, the relevant code does

```python
   combiner = hl.vds.new_combiner(
        gvcf_paths=[…a bunch of gvcf_paths…],
        output_path=str(vds_path),
         […etc…]
   )           
   combiner.run()

   vds = hl.vds.read_vds(str(vds_path))
   vds = hl.vds.split_multi(vds, filter_changed_loci=True)
```

This raises an exception within `split_multi()`:

```
AttributeError: 'StringExpression' object has no attribute 'is_non_ref'
```

As can be seen from the full log, this exception occurs when _hail/python/hail/experimental/sparse_mt/sparse_split_multi.py_'s `transform_entries()` looks at the LPGT entry and tries to use a `CallExpression` method on it.

Tracing the vds through the combiner code, we can see that the returned data structure lists the LPGT entry as `str` rather than `call` as in Hail 0.2.119:

```
----------------------------------------
Global fields:
    None
----------------------------------------
Column fields:
    's': str
----------------------------------------
Row fields:
    'locus': locus<GRCh38>
    'alleles': array<str>
    'rsid': str
----------------------------------------
Entry fields:
    'LA': array<int32>
    'LGT': call
    'LAD': array<int32>
    'LPGT': str           # BROKEN, should be "call"
    'LPL': array<int32>
    'RGQ': int32
    'gvcf_info': struct {
        […etc…]
```

Hence the problem appears to be in the combining and I suspect may have been caused by PR #13206.

Any hints on where this field may have been reverted to a `StringExpression` in the new combiner code? I can try to debug this further, or is this enough to go on for those familiar with this code?

### Version

0.2.120 (worked as expected in 0.2.119 and prior)

### Relevant log output

```shell
cpg_workflows/large_cohort/dense_subset.py:24: in run
    vds = hl.vds.split_multi(vds, filter_changed_loci=True)
<decorator-gen-1858>:2: in split_multi
    ???
/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/hail/typecheck/check.py:584: in wrapper
    return __original_func(*args_, **kwargs_)
/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/hail/vds/methods.py:766: in split_multi
    variant_data = hl.experimental.sparse_split_multi(vds.variant_data, filter_changed_loci=filter_changed_loci)
/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/hail/experimental/sparse_mt/sparse_split_multi.py:206: in sparse_split_multi
    entries: ds[entries].map(transform_entries)
<decorator-gen-564>:2: in map
    ???
/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/hail/typecheck/check.py:584: in wrapper
    return __original_func(*args_, **kwargs_)
/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/hail/expr/expressions/typed_expressions.py:309: in map
    array_map = hl.array(self)._ir_lambda_method(transform_ir, f, self._type.element_type, lambda t: self._type.__class__(t))
/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/hail/expr/expressions/base_expression.py:706: in _ir_lambda_method
    f(expressions.construct_variable(new_id, input_type, self._indices, self._aggregations)))
/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/hail/typecheck/check.py:371: in f
    ret = x(*args)
/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/hail/experimental/sparse_mt/sparse_split_multi.py:199: in transform_entries
    return hl.bind(with_local_a_index, lai)
<decorator-gen-746>:2: in bind
    ???
/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/hail/typecheck/check.py:584: in wrapper
    return __original_func(*args_, **kwargs_)
/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/hail/expr/functions.py:537: in bind
    lambda_result = to_expr(f(*args))
/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/hail/experimental/sparse_mt/sparse_split_multi.py:190: in with_local_a_index
    return hl.bind(with_pl, new_pl)
<decorator-gen-746>:2: in bind
    ???
/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/hail/typecheck/check.py:584: in wrapper
    return __original_func(*args_, **kwargs_)
/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/hail/expr/functions.py:537: in bind
    lambda_result = to_expr(f(*args))
/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/hail/experimental/sparse_mt/sparse_split_multi.py:156: in with_pl
    new_exprs['PGT'] = hl.rbind(
/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/hail/expr/functions.py:588: in rbind
    return hl.bind(f, *args, _ctx=_ctx)
<decorator-gen-746>:2: in bind
    ???
/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/hail/typecheck/check.py:584: in wrapper
    return __original_func(*args_, **kwargs_)
/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/hail/expr/functions.py:537: in bind
    lambda_result = to_expr(f(*args))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

lpgt = <StringExpression of type str>

>   lambda lpgt: hl.if_else(lpgt.is_non_ref(), hl.downcode(lpgt, hl.or_else(
        local_a_index, hl.len(old_entry.LA))), lpgt))
E       AttributeError: 'StringExpression' object has no attribute 'is_non_ref'

/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/hail/experimental/sparse_mt/sparse_split_multi.py:158: AttributeError
```

**Comment by chrisvittal** [comment]
resolved by #13364
