### ISSUE TITLE
[query] Support Spark 3.5.x

### ISSUE THREAD

**Issue by daniel-goldstein** [hail-is/hail#13971]
### What happened?

At time of writing, building hail with `SPARK_VERSION=3.4.0` errors with the following message:

```
hail/src/main/scala/is/hail/HailContext.scala:119:21: value implOpMulMatrix_DMD_DVD_eq_DVD is not a member of object breeze.linalg.DenseMatrix
```

This is due to a major version upgrade and breaking change in the Breeze library on which spark and hail depend. The exact error is a rename and refactor. The method `DenseMatrix.implOpMulMatrix_DMD_DVD_eq_DVD` is now `HasOps.impl_OpMulMatrix_DMD_DVD_eq_DVD`. Notice the method name change and the fact that `HasOps` does not exist in the version of Breeze (1.x) that is used in Spark 3.3.

Hail should build with Spark 3.4, but since we only officially support one version of Spark (whichever Dataproc currently is running), it would be reasonable to wait to fully upgrade to Spark 3.4 when [Dataproc 2.2](https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-release-2.2) is GA instead of trying to do something hacky to support both versions of Breeze.

### Version

0.2.126

**Comment by daniel-goldstein** [comment]
This patch and the contents of #13970 was sufficient to successfully run `make -C hail install SPARK_VERSION=3.4.0`.

```diff
diff --git a/hail/build.gradle b/hail/build.gradle
index 1b65904484..d1feb0e578 100644
--- a/hail/build.gradle
+++ b/hail/build.gradle
@@ -40,7 +40,7 @@ tasks.withType(JavaCompile) {
 }
 
 project.ext {
-    breezeVersion = "1.1"
+    breezeVersion = "2.1.0"
 
     sparkVersion = System.getProperty("spark.version", "3.3.0")
 
diff --git a/hail/src/main/scala/is/hail/HailContext.scala b/hail/src/main/scala/is/hail/HailContext.scala
index 4e4063378b..4d2f9056a5 100644
--- a/hail/src/main/scala/is/hail/HailContext.scala
+++ b/hail/src/main/scala/is/hail/HailContext.scala
@@ -113,10 +113,10 @@ object HailContext {
 
     {
       import breeze.linalg._
-      import breeze.linalg.operators.{BinaryRegistry, OpMulMatrix}
+      import breeze.linalg.operators.{BinaryRegistry, HasOps, OpMulMatrix}
 
       implicitly[BinaryRegistry[DenseMatrix[Double], Vector[Double], OpMulMatrix.type, DenseVector[Double]]].register(
-        DenseMatrix.implOpMulMatrix_DMD_DVD_eq_DVD)
+        HasOps.impl_OpMulMatrix_DMD_DVD_eq_DVD)
     }
 
     theContext = new HailContext(backend, branchingFactor, optimizerIterations)
```

**Comment by alexiswl** [comment]
This also unlocks using hail for DataBricks runtime 13-3 LTS

 https://discuss.hail.is/t/databricks-13-3-lts-with-spark-3-4-1/3673

**Comment by danking** [comment]
We will be skipping Spark 3.4.x and jumping to Spark 3.5.x because Google Dataproc has skipped to 3.5.x. https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-release-2.2
