### ISSUE TITLE
Document Scala version dependency

### ISSUE THREAD

**Issue by hammer** [hail-is/hail#8009]
I tried to run Hail with Spark 2.4.4 built for Scala 2.12, and it did not work. It does work with Spark 2.4.4 built for Scala 2.11.

Here's the error I got with Scala 2.12:
> Py4JJavaError: An error occurred while calling z:is.hail.HailContext.apply.
> : java.lang.NoSuchMethodError: scala/Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps; (loaded from file:/home/hammer/codebox/spark-2.4.4-bin-without-hadoop-scala-2.12/jars/scala-library-2.12.8.jar by sun.misc.Launcher$AppClassLoader@ac1080fa) called from class is.hail.HailContext$ (loaded from file:/home/hammer/anaconda3/lib/python3.7/site-packages/hail/hail-all-spark.jar by sun.misc.Launcher$AppClassLoader@ac1080fa).
> 	at is.hail.HailContext$.majorMinor$1(HailContext.scala:71)
> 	at is.hail.HailContext$.checkSparkCompatibility(HailContext.scala:73)
> 	at is.hail.HailContext$.createSparkConf(HailContext.scala:84)
> 	at is.hail.HailContext$.configureAndCreateSparkContext(HailContext.scala:134)
> 	at is.hail.HailContext$.apply(HailContext.scala:270)
> 	at is.hail.HailContext.apply(HailContext.scala)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
> 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
> 	at py4j.Gateway.invoke(Gateway.java:282)
> 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
> 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
> 	at py4j.GatewayConnection.run(GatewayConnection.java:238)
> 	at java.lang.Thread.run(Thread.java:819)
>

**Comment by tpoterba** [comment]
we hardcode the scala version to 2.11 at the moment:

https://github.com/hail-is/hail/blob/9ef5ebb362e70633a8e29b81768ad92f2853e6cb/hail/build.gradle#L37-L38

so this is pretty much to be expected. We'll make this flexible when Google Dataproc releases a GA image using 2.12, but could certainly document it before then.

**Comment by hammer** [comment]
Got it; for my own future reference I'm going to link to the [Cloud Dataproc Image version list](https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-versions) and note that the 1.5 series, currently in [preview](https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-release-1.5), does use Scala 2.12.

**Comment by tpoterba** [comment]
We'll probably switch to 2.12 when there's a PySpark release with 2.12, which there isn't in the 2.4 series (aside from one patch version (2.4.2, nothing else). This has been moved to Asana for task scheduling.

**Comment by hammer** [comment]
@tpoterba is the Asana you mention public?

**Comment by tpoterba** [comment]
It's not. We're rethinking what issues should be, and I've moved ~300 today that were an assortment of feature ideas and possible improvements from team members over the last several years. I think this is actually one that should stay open -- we shouldn't close issues from external community members without a fix, or a discussion about why we won't fix.

**Comment by tpoterba** [comment]
we're thinking that GitHub issues should just be bug reports / problems with a clear fix that can be addressed with a maximum of a few commits. Feature requests should be in the forum, development discuss in in dev.hail.is or Zulip dev channel.

**Comment by johnc1231** [comment]
We now allow the Scala version to be specified (added in order to support Spark 3). I think that resolves this issue? If not you can reopen Tim.
