### ISSUE TITLE
Bokeh dependency on jinja2 failing with latest version

### ISSUE THREAD

**Issue by williambrandler** [hail-is/hail#11705]
I am testing hail build on spark3 (v0.2.89, spark 3.1.2) and getting the following error with jinja2 (see below).
From the error it seems like this is due to Hail's dependency of bokeh using the latest version of jinja2

Downgrading jinja2 to 3.0.0 solves the problem, and it seems like other people have seen this too with the latest release of jinja2:

https://github.com/holoviz/panel/issues/3260

This may be transient and may be solved by bokeh / jinja2 folks but thought I'd let you know in case you hit this issue

```
../conda/envs/glow/lib/python3.7/site-packages/bokeh/core/templates.py:43: in <module>
from jinja2 import Environment, Markup, FileSystemLoader
E   ImportError: cannot import name 'Markup' from 'jinja2' (/home/circleci/conda/envs/lib/python3.7/site-packages/jinja2/__init__.py)
[error] java.lang.IllegalArgumentException: requirement failed: Python tests in Hail environment failed
[error] 	at scala.Predef$.require(Predef.scala:281)
[error] 	at $1fb87e3247134917ca70$.$anonfun$pythonSettings$14(build.sbt:288)
[error] 	at $1fb87e3247134917ca70$.$anonfun$pythonSettings$14$adapted(build.sbt:278)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:289)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (hail / hailtest) java.lang.IllegalArgumentException: requirement failed: Python tests in Hail environment failed
```

To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: 
https://discuss.hail.is/

Please include the full Hail version and as much detail as possible.

-----------------------------------------------------------------------------

**Comment by daniel-goldstein** [comment]
Hi @williambrandler, it does seem like everyone is getting hit with this issue. We pinned Jinja2 to 3.0.3 once this broke our tests and it should be fixed now. I'm going to close this issue but if you still experience these problems on the latest release please re-open and we'll address it promptly.
